version: 2
updates:
- package-ecosystem: gradle
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: junit:junit
    versions:
    - 4.13.1
