language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
service:
  - docker
jobs:
  include:
    - stage: code scan
      script:
        - python ./configsonar.py $SONAR_ORG:Java-client:$TRAVIS_BRANCH $SONAR_ORG:Java-client:$TRAVIS_BRANCH $SONAR_ORG javaclientgate2 $SONAR_TOKEN
        - gradle sonarqube --stacktrace -PsonarProjectKey=$SONAR_ORG:Java-client:$TRAVIS_BRANCH -PsonarProjectName=$SONAR_ORG:Java-client:$TRAVIS_BRANCH -PsonarOrg=$SONAR_ORG -Dsonar.branch.name=master
        # - gradle sonarqube --stacktrace -Dsonar.ProjectKey=$SONAR_ORG:Java-client:$TRAVIS_BRANCH -Dsonar.ProjectName=$SONAR_ORG:Java-client:$TRAVIS_BRANCH -Dsonar.organization=$SONAR_ORG -Dsonar.branch.name=master
        - chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeys=$SONAR_ORG:Java-client -BranchName=$TRAVIS_BRANCH
