language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
service:
  - docker
jobs:
  include:
    # - stage: unit test
    #   script:
    #   - cd server
    #   - gradle build
    # - stage: code scan
    #   script:
    #   - cd server
    #   - gradle sonarqube -PsonarProjectKey=$SONAR_PROJECT_KEY -PsonarProjectName=$SONAR_PROJECT_NAME -PsonarOrg=$SONAR_ORG
    - stage: auto test
      script:
      - cd build && jar -cvf0m service.jar ./META-INF/MANIFEST.MF ./org/ ./BOOT-INF/
      - cp service.jar ../
      - cd ..
      - docker build -t singleton .
      - docker run -p 8090:8090 --name singleton singleton
      - docker ps
      - sleep 20
      - echo | curl https://127.0.0.1:8090/i18n/api/v2/formatting/patterns/locales/zh-Hans?scope=dates -k
      - echo | curl https://127.0.0.1:8090/i18n/api/v2/formatting/patterns/locales/zh-Hans?scope=dates
      - docker exec singleton bash -c 'git clone --branch=devops https://github.com/singleton-demo/ci.git devops && cd devops/autotest/server/APITest && cp l10n / && gradle build && java -cp "target/*:resource/*" org.testng.TestNG testng.xml'
