dist: trusty
language: node_js
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
node_js:
  - "7"
python:
  - "3.4"
jobs:
  include:
    - stage: code scan
      script:
        - npm install npm
        - npm install tslint
        - npm install typescript
        - tsc -v
        - python ./configsonar.py $SONAR_ORG:singleton' '$TRAVIS_BRANCH $SONAR_ORG:singleton:$TRAVIS_BRANCH $SONAR_ORG jsclientgate $SONAR_TOKEN
        - sonar-scanner -Dsonar.sources=. -Dsonar.projectName=$SONAR_ORG:singleton -Dsonar.projectKey=$SONAR_ORG:singleton -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.branch.name=$TRAVIS_BRANCH
        - chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeys=$SONAR_ORG:singleton -BranchName=$TRAVIS_BRANCH
