language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
service:
  - docker
jobs:
  include:
    - stage: unit test
      script:
      - cd server
      - gradle build
    - stage: code scan
      script:
      - cd server
      - gradle sonarqube -PsonarProjectKey=$SONAR_PROJECT_KEY -PsonarProjectName=$SONAR_PROJECT_NAME -PsonarOrg=$SONAR_ORG
    - stage: auto test
      script:
      - cd build && jar -cvf0m service.jar ./META-INF/MANIFEST.MF ./org/ ./BOOT-INF/ ./resources.zip
      - cp service.jar ../
      - cd ..
      - docker build -t singleton .
      - docker run -d -p 8090:8090 --name singleton singleton
      - docker ps
      - sleep 20
      - docker ps
      - git clone --branch=devops https://github.com/singleton-demo/ci.git devops
      - ls
      - cd devops/autotest/server/APITest && gradle build
      - docker cp l10n singleton:/
      - java -cp "target/*:resource/*" org.testng.TestNG testng.xml
