dist: trusty
language: node_js
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
node_js:
  - "7"
python:
  - "3.4"
jobs:
  include:
    - stage: code scan
      script:
        - npm install npm
        - npm install tslint
        - npm install typescript
        - tsc -v
        - python ./configsonar.py $SONAR_ORG:singleton' '$TRAVIS_BRANCH $SONAR_ORG:singleton:$TRAVIS_BRANCH $SONAR_ORG jsclientgate $SONAR_TOKEN
        - sonar-scanner -Dsonar.sources=. -Dsonar.projectName=$SONAR_ORG:singleton' '$TRAVIS_BRANCH -Dsonar.projectKey=$SONAR_ORG:singleton:$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN
        - chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeys=$SONAR_ORG:singleton -BranchName=$TRAVIS_BRANCH
    - stage: unit test
      script:
        - npm install --registry https://registry.npmjs.org
        - npm run test
        - npm link
    - stage: auto test
      script:
        - git clone --branch=devops https://github.com/singleton-demo/ci.git devops
        - cd test/client/jscoresdk
        - npm install --registry https://registry.npmjs.org
        - npm link  @vip/vip-core-sdk
        - ./node_modules/.bin/jest
