language: java
python:
  - "3.4"
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
install:
  - sudo pip3 intall requests
jobs:
  include:
    - stage: unit test
      script:
      - cd server
      - gradle build
    - stage: code scan
      script:
      - cd server
      - python ./configsonar.py '$SONAR_ORG:singleton $TRAVIS_BRANCH' $SONAR_ORG:singleton:$TRAVIS_BRANCH $SONAR_ORG testgate
      - gradle sonarqube -Dsonar.projectName=$SONAR_ORG:singleton -Dsonar.projectKey=$SONAR_ORG:singleton -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.branch=$TRAVIS_BRANCH -Dsonar.qualitygate=server-gate
