language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
service:
  - docker
jobs:
  include:
    - stage: unit test
      script:
      - cd client
      - gradle build
    - stage: code scan
      script:
      - python ./configsonar.py $SONAR_ORG:javaclient+' '+$TRAVIS_BRANCH $SONAR_ORG:javaclient:$TRAVIS_BRANCH $SONAR_ORG javaclientgate $SONAR_TOKEN
      - cd server
      - gradle sonarqube -Dsonar.projectName=$SONAR_ORG:javaclient -Dsonar.projectKey=$SONAR_ORG:javaclient -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.branch=$TRAVIS_BRANCH
      - cd .. && chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeys=$SONAR_ORG:singleton -BranchName=$TRAVIS_BRANCH
